config/routes.rb
Rails.application.routes.draw do
  get 'users_controller/destroy'

  root 'sessions#index'
  get 'about', to: 'articles#about'
  get 'gallery', to: 'articles#gallery'
  get 'signup', to: 'users#new'
  get 'articles', to: 'users#articles'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, except: [:new]

  resources :articles, except: [:index] # gives us an articles path (CRUD)

  resources :categories, except: [:delete] # do not want a delete for categories

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  # Destroys all articles if they are deleted
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase}
  # ensures that user is unique
  validates :username, presence: true, uniqueness: {case_sensitive: false},length: {minimum: 5, maximum: 25}
  VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # sets set_user method to the ones inside the []
  before_action :set_user, only: [:edit, :update, :show]

  before_action :require_same_user, only: [:edit, :update, :destroy]

  before_action :require_admin, only: [:destroy]

  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page], :per_page => 5)
  end

  def create
    #debugger
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the blog, #{@user.username}."
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated!"
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], :per_page => 4)
  end

  def articles
    @articles = Article.paginate(page: params[:page], :per_page => 5)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles have been deleted"
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  # Before action sets this to the edit, show, and update
  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "You can only edit your own account."
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin users can perform that action."
      redirect_to root_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="text-center">
  <% if @user.errors.any? %>
      <p>Error messages</p>
      <% @user.errors.full_messages.each do |m| %>
          <li><%= m %></li>
      <% end %>
  <% end %>
</div>

<div class="text-center">
  <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :username %>
        <%= f.text_field :username, :class => 'form-control center-block', :placeholder => "Enter username." %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, :class => 'form-control center-block', :placeholder => "Enter email." %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, :class => 'form-control center-block', :placeholder => "Enter password."  %>
      </div>

      <div class="form-group">
        <!-- Checks if user is new or updating their account -->
        <%= f.submit @user.new_record? ? "Sign up" : "Update account", :class=> 'btn btn-success'%>
      </div>
  <% end %>
</div>

app/views/users/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <%= link_to "Home", user_path(current_user), class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li><%= link_to "Create New Article", new_article_path%></li>
          <li><%= link_to "View All Articles", articles_path%></li>
          <li><%= link_to "View All Categories", categories_path%></li>
          <li><%= link_to "View Users", users_path%></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav pull-right">
        <% if logged_in? %>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User Actions <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Edit profile", edit_user_path(current_user), class: "btn" %></li>
                  <% if logged_in? and current_user.admin? %>
                      <li><%= link_to "Create Category", new_category_path, class: "btn btn-success" %></li>
                <% end %>
                  <li><%= link_to "Logout", logout_path, method: :delete, class: "btn btn-danger"%></li>
                </ul>
              </li>
            </ul>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!-- Shows messages -->
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
        <div class='alert alert-<%="#{name}" %>'>
          <a href="#" class="close" data-dismiss="alert">×</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
    <% end %>
  </div>
</div>

app/views/users/articles.html.erb
<%= render 'users/header' %>
<h1 class="text-center">All Articles</h1>

<div class="text-center">
  <%= will_paginate @articles, renderer: BootstrapPagination::Rails %>
</div>
<%= render 'layouts/articles', obj: @articles %>

app/views/users/edit.html.erb
<%= render 'header' %>

<h1 class="text-center">Edit your account.</h1>
<hr>

<%= render 'form' %>

app/views/users/index.html.erb
<%= render 'header' %>

<h1 class="text-center">All Bloggers</h1>

<hr>

<div class="text-center">
  <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
</div>

<% @users.each do |user| %>
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <%= link_to gravatar_for(user), user_path(user) %>
          <div class="article-title text-center">
            <%= link_to user.username, user_path(user) %>
          </div>
          <p class="text-center"><%= pluralize(user.articles.count, "article") if user.articles %></p>
          <% if logged_in? && current_user.admin? %>
            <div class="text-center"><%= link_to "Delete this user", user_path(user), method: :delete, data: {confirm: "Are you sure you want to delete this user and all articles?"}, class: "btn btn-danger" %></div>
          <% end %>
        </div>
      </div>
<% end %>

app/views/users/new.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li><a href="/gallery">Gallery</a></li>
        <li><a href="/about">About Me</a></li>-->
        <li><%= link_to "Login", login_path %></a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<h1 class="text-center">Sign up.</h1>

<hr>

<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'header' %>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 80%>
  </div>
</div>

<h3 class="text-center" style="color: lightgray !important;"><%= @user.username %>'s articles.</h3>

<div class="text-center">
  <%= will_paginate @user_articles, renderer: BootstrapPagination::Rails %>
</div>

<%= render 'layouts/articles', obj: @user_articles %>