config/routes.rb
Rails.application.routes.draw do
  get 'users_controller/destroy'

  root 'sessions#index'
  get 'about', to: 'articles#about'
  get 'gallery', to: 'articles#gallery'
  get 'signup', to: 'users#new'
  get 'articles', to: 'users#articles'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, except: [:new]

  resources :articles, except: [:index] # gives us an articles path (CRUD)

  resources :categories, except: [:delete] # do not want a delete for categories

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    
  end

  def about

  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.haml
%nav.navbar.navbar-inverse{role: "navigation"}
  / Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", type: "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand Jason's Blog
  / Collect the nav links, forms, and other content for toggling
  .collapse.navbar-collapse.navbar-ex1-collapse
    %ul.nav.navbar-nav
      %li
        %a{href: "/"} Home
      %li.active
        %a{href: "/about"} About
    %form.navbar-form.navbar-right{role: "search"}
      .form-group
        %input.form-control{placeholder: "Search", type: "text"}/
      %button.btn.btn-success{type: "submit"} Submit

%h1.container.text-center= "About Page"

-# =link_to "Home", root_path #goes to the root page

app/views/welcome/home.html.haml
%nav.navbar.navbar-inverse{role: "navigation"}
  / Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", type: "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand Jason's Blog
  / Collect the nav links, forms, and other content for toggling
  .collapse.navbar-collapse.navbar-ex1-collapse
    %ul.nav.navbar-nav
      %li.active
        %a{href: "/"} Home
      %li
        %a{href: "/about"} About
    %form.navbar-form.navbar-right{role: "search"}
      .form-group
        %input.form-control{placeholder: "Search", type: "text"}/
      %button.btn.btn-success{type: "submit"} Submit

%h1.container.text-center= "Home Page"


-# = link_to "About", about_path #about path if using home as root

.content
  -# %p.color-change= "This is where you go to visit first."