config/routes.rb
Rails.application.routes.draw do
  get 'users_controller/destroy'

  root 'sessions#index'
  get 'about', to: 'articles#about'
  get 'gallery', to: 'articles#gallery'
  get 'signup', to: 'users#new'
  get 'articles', to: 'users#articles'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, except: [:new]

  resources :articles, except: [:index] # gives us an articles path (CRUD)

  resources :categories, except: [:delete] # do not want a delete for categories

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories # has many articles
  validates :name, presence: true, length: {minimum: 5, maximum: 25}
  validates_uniqueness_of :name # ensures that name is unique
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, except: [:index, :show]
  def index
    @categories = Category.paginate(page: params[:page], :per_page => 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], :per_page => 5)
  end

  private
  # requires the parameter name
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "You need to be an admin to perform this action."
      redirect_to categories_path
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<div class="text-center">
  <% if @category.errors.any? %>
      <p>Error messages</p>
      <% @category.errors.full_messages.each do |m| %>
          <li><%= m %></li>
      <% end %>
  <% end %>
</div>

<div class="text-center">
  <%= form_for @category do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, :class => 'form-control center-block', :placeholder => "Enter category name." %>
      </div>

      <div class="form-group">
        <%= f.submit "Submit", :class=> 'btn btn-success'%>
      </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
<%= render 'users/header' %>

<h1 class="text-center">Edit category name</h1>
<hr>

<%= render 'categories/form' %>

app/views/categories/index.html.erb
<%= render 'users/header' %>

<h1 class="text-center">All Categories</h1>
<hr>


<div class="text-center">
<%= will_paginate @categories, renderer: BootstrapPagination::Rails %>
</div>

<% @categories.each do |category| %>
    <div class="row">
      <div class="well col-md-4 col-md-offset-4 text-center">
          <%= link_to "#{category.name}", category_path(category) %>
        <hr>
        <p class="text-center"><%= pluralize(category.articles.count, "article") %></p>
      </div>
    </div>

<% end %>

app/views/categories/new.html.erb
<%= render 'users/header' %>

<h1 class="text-center">Create new category</h1>
<hr>

<%= render 'categories/form' %>

app/views/categories/show.html.erb
<%= render 'users/header' %>

<h1 class="text-center">Category: <%= @category.name %></h1>
<br>
<% if logged_in? and current_user.admin? %>
  <div class="text-center">
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-warning" %>
  </div>
<% end %>
<hr>


<div class="text-center">
  <%= will_paginate @category_articles, renderer: BootstrapPagination::Rails %>
</div>
<%= render 'layouts/articles', obj: @category_articles %>