config/routes.rb
Rails.application.routes.draw do
  get 'users_controller/destroy'

  root 'sessions#index'
  get 'about', to: 'articles#about'
  get 'gallery', to: 'articles#gallery'
  get 'signup', to: 'users#new'
  get 'articles', to: 'users#articles'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, except: [:new]

  resources :articles, except: [:index] # gives us an articles path (CRUD)

  resources :categories, except: [:delete] # do not want a delete for categories

end

app/views/layouts/_articles.html.erb
<!-- shows all articles -->
<% obj.each do |article| %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2 well well-sm">

        <%= link_to article.title, article_path(article), :class => "article-title" %>

        <hr>

        <div class="article-desc">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
            <small>Created by: <%= article.user.username %> at <%= article.user.created_at.localtime %>

            </small>
          </div>
        </div>

        <hr>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
        <%= link_to "Edit", edit_article_path(article), :class => "btn btn-success" %>
        <!-- Lets rails know that this is specifically for a delete, and the confirm is an alert box. -->
        <%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"}, :class => "btn btn-danger" %>
        <% end%>
        <hr>
        <% if article.categories.any? %>
            <p class="text-center">Categories: <%= render article.categories %></p>
        <% end %>
      </div>
    </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li><a href="/gallery">Gallery</a></li>
        <li><a href="/about">About Me</a></li>-->
        <li><%= link_to "Sign up", signup_path %></a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!-- Shows messages -->
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
        <div class='alert alert-<%="#{name}" %>'>
          <a href="#" class="close" data-dismiss="alert">×</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogproject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

<footer class="footer">
  <div class="container">
    <hr>
    <p class="text-center" style="color:white;">Made by: Jason C</p>
  </div>
</footer>

<!-- Show debug in html only if environment is development -->
</body>
</html>